In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv('netflix_customer_churn.csv')

In [4]:
df.head()

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

## Checking null values

In [5]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [6]:
pd.crosstab(df["payment_method"], df["churned"],normalize="index")

churned                0         1
payment_method
Credit Card     0.564234  0.435766
Crypto          0.403015  0.596985
Debit Card      0.563107  0.436893
Gift Card       0.422131  0.577869
PayPal          0.529240  0.470760

In [7]:
pd.crosstab(df["favorite_genre"], df["churned"],normalize="index")

churned                0         1
favorite_genre
Action          0.476327  0.523673
Comedy          0.500730  0.499270
Documentary     0.492455  0.507545
Drama           0.477428  0.522572
Horror          0.485273  0.514727
Romance         0.517241  0.482759
Sci-Fi          0.529167  0.470833

In [8]:
df.drop(columns=['customer_id','favorite_genre'],inplace=True)

In [9]:
df['churned'].value_counts()

churned
1    2515
0    2485
Name: count, dtype: int64

## Train test split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['churned'],axis=1),
                                                 df['churned'],
                                                 test_size=0.2,
                                                random_state=42)

In [11]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>

In [12]:
X_train.head()

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,payment_method,number_of_profiles,avg_watch_time_per_day
4227,54,Other,Premium,9.80,56,North America,Tablet,17.99,Crypto,4,0.17
4676,31,Other,Basic,10.38,42,North America,Tablet,8.99,Debit Card,1,0.24
800,59,Other,Basic,20.13,6,Africa,Mobile,8.99,Credit Card,1,2.88
3671,45,Female,Basic,9.77,16,Asia,Laptop,8.99,Gift Card,2,0.57
4193,36,Male,Standard,9.10,2,North America,Tablet,13.99,Debit Card,2,3.03

In [13]:
y_train.sample(10)

4641    0
4073    1
1435    1
4447    1
3131    1
817     1
1527    0
359     1
1385    0
4958    0
Name: churned, dtype: int64

## Ordinal Encoding and One Hot Encoding using Column Transformer

In [14]:
trf1 = ColumnTransformer([
     ('ord_subscription',
     OrdinalEncoder(categories=[['Basic','Standard','Premium']]),
     [2]),
    ('ohe_cat',
     OneHotEncoder(handle_unknown='ignore'),
     [1,5,6,8])
], remainder='passthrough')

## Feature Selection

In [15]:
trf2 = SelectKBest(score_func=chi2,k=8)

## Training the model

In [16]:
trf3 = DecisionTreeClassifier()

## Creating Pipeline

In [17]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3)
])

In [18]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ord_subscription',
                                                  OrdinalEncoder(categories=[['Basic',
                                                                              'Standard',
                                                                              'Premium']]),
                                                  [2]),
                                                 ('ohe_cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  [1, 5, 6, 8])])),
                ('trf2',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x000001F170D1F7E0>)),
                ('trf3', DecisionTreeClassifier())])

In [19]:
X_train.select_dtypes(include="object").columns

Index(['gender', 'subscription_type', 'region', 'device', 'payment_method'], dtype='object')

## Exploring Pipeline

In [20]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('ord_subscription',
                                  OrdinalEncoder(categories=[['Basic',
                                                              'Standard',
                                                              'Premium']]),
                                  [2]),
                                 ('ohe_cat',
                                  OneHotEncoder(handle_unknown='ignore'),
                                  [1, 5, 6, 8])]),
 'trf2': SelectKBest(k=8, score_func=<function chi2 at 0x000001F170D1F7E0>),
 'trf3': DecisionTreeClassifier()}

In [21]:
# Display Pipeline
from sklearn import set_config
set_config(display='diagram')

In [22]:
y_pred = pipe.predict(X_test)

In [23]:
y_pred

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

## Checking Scores

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = pipe.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy: 0.988
[[492   6]
 [  6 496]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       498
           1       0.99      0.99      0.99       502

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

In [25]:
pipe.score(X_train, y_train)

1.0

## Cross Validation using Pipeline

In [26]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.9837499999999999)

## GridSearch using Pipeline

In [27]:
params = {
'trf3__max_depth':[3,5,7,None],
'trf3__min_samples_split':[2,5,10],
'trf3__min_samples_leaf':[1,2,4]
}

In [28]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ord_subscription',
                                                                         OrdinalEncoder(categories=[['Basic',
                                                                                                     'Standard',
                                                                                                     'Premium']]),
                                                                         [2]),
                                                                        ('ohe_cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         [1, 5,
                                                                          6,
                                                                          8])])),
                                       ('trf2',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x000001F170D1F7E0>)),
                                       ('trf3', DecisionTreeClassifier())]),
             param_grid={'trf3__max_depth': [3, 5, 7, None],
                         'trf3__min_samples_leaf': [1, 2, 4],
                         'trf3__min_samples_split': [2, 5, 10]},
             scoring='accuracy')

In [29]:
grid.best_score_

np.float64(0.984)

In [30]:
grid.best_params_

{'trf3__max_depth': None,
 'trf3__min_samples_leaf': 2,
 'trf3__min_samples_split': 2}

## Exporting Pipeline

In [31]:
import pickle
with open("pipe.pkl","wb") as f:
    pickle.dump(pipe,f)